version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=lara_demo_quiz
      - DB_USERNAME=root
      - DB_PASSWORD=
      - COMPOSER_MEMORY_LIMIT=-1
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=lara_demo_quiz
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data:/var/lib/mysql
  node:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - .:/var/www/html
    depends_on:
        - app
    environment:
        - NODE_VERSION=18
